[package]
name = "rust-aes256"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
rand = "0.8"
base64 = "0.22.1"
aes = "0.7"
block-modes = "0.8"
hex = "0.4"
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
